teamSubnet = ["10.0.0.", "10.32.0.", "10.64.0.", "10.96.0."]

teamMachine = [
  {
    "name": "AD",
    "ip_ext": "1",
    "flagPath": "C:\\\\Users\\\\admin\\\\Desktop\\\\flag.txt",
  },
  {
    "name": "Win7_1",
    "ip_ext": "2",
    "flagPath": "C:\\\\Users\\\\admin\\\\Desktop\\\\flag.txt",
  },
  {
    "name": "Win7_2",
    "ip_ext": "3",
    "flagPath": "C:\\\\Users\\\\admin\\\\Desktop\\\\flag.txt",
  },
  {
    "name": "Ubuntu_1",
    "ip_ext": "4",
    "flagPath": "/root/flag.txt",
  },
  {
    "name": "Ubuntu_2",
    "ip_ext": "5",
    "flagPath": "/root/flag.txt",
  },
  {
    "name": "Ubuntu_3",
    "ip_ext": "6",
    "flagPath": "/root/flag.txt",
  },
]

machine = [
  {
    "name": "AD",
    "flag": 1500,
    "Service": [
      {
        "name": "ProxyLogon",
        "patch": 1125,
        "block": -1000,
        "offline": -500,
        "port": 587,
        "checkpatch": "/root/scripts/proxylogon/patch.sh",
        "checknormal": "/root/scripts/proxylogon/normal.sh",
      },
      {
        "name": "Zerologon",
        "patch": 1125,
        "block": -1000,
        "offline": -500,
        "port": 445,
        "checkpatch": "/root/scripts/zerologon/patch.sh",
        "checknormal": "/root/scripts/zerologon/normal.sh",
      },
    ],
  },
  {
    "name": "Win7_1",
    "flag": 900,
    "Service": [
      {
        "name": "ms17010",
        "patch": 300,
        "block": -300,
        "offline": -150,
        "port": 445,
        "checkpatch": "/root/scripts/MS17_010/patch.sh",
        "checknormal": "/root/scripts/MS17_010/normal.sh",
      },
      {
        "name": "bluekeep",
        "patch": 300,
        "block": -300,
        "offline": -150,
        "port": 3389,
        "checkpatch": "/root/scripts/bluekeep/patch.sh",
        "checknormal": "/root/scripts/bluekeep/normal.sh",
      },
      {
        "name": "cookie",
        "patch": 300,
        "block": -300,
        "offline": -150,
        "port": 81,
        "checkpatch": "/root/scripts/cookie/patch.sh",
        "checknormal": "/root/scripts/cookie/normal.sh",
      },
      # {
      #   "name": "Pwn",
      #   "patch": 450,
      #   "block": -300,
      #   "offline": -150,
      #   "port": 7788,
      #   "checkpatch": "/root/scripts/linux_pwn/patch.sh",
      #   "checknormal": "/root/scripts/linux_pwn/normal.sh",
      # },
    ],
  },
  {
    "name": "Win7_2",
    "flag": 900,
    "Service": [
      {
        "name": "XXE",
        "patch": 550,
        "block": -400,
        "offline": -200,
        "port": 80,
        "checkpatch": "/root/scripts/XXE/patch.sh",
        "checknormal": "/root/scripts/XXE/normal.sh",
      },
      {
        "name": "ms17010",
        "patch": 400,
        "block": -400,
        "offline": -200,
        "port": 445,
        "checkpatch": "/root/scripts/MS17_010/patch.sh",
        "checknormal": "/root/scripts/MS17_010/normal.sh",
      },
      {
        "name": "bluekeep",
        "patch": 400,
        "block": -400,
        "offline": -200,
        "port": 3389,
        "checkpatch": "/root/scripts/bluekeep/patch.sh",
        "checknormal": "/root/scripts/bluekeep/normal.sh",
      },
    ],
  },
  {
    "name": "Ubuntu_1",
    "flag": 750,
    "Service": [
      {
        "name": "apache_rce",
        "patch": 300,
        "block": -320,
        "offline": -160,
        "port": 80,
        "checkpatch": "/root/scripts/apache/patch.sh",
        "checknormal": "/root/scripts/apache/normal.sh",
      },
      {
        "name": "wordpress",
        "patch": 375,
        "block": -320,
        "offline": -160,
        "port": 80,
        "checkpatch": "/root/scripts/wordpress_RCE/patch.sh",
        "checknormal": "/root/scripts/wordpress_RCE/normal.sh",
      },
      {
        "name": "weak_password",
        "patch": 375,
        "block": -320,
        "offline": -160,
        "port": 80,
        "checkpatch": "/root/scripts/weak_password/patch.sh",
        "checknormal": "/root/scripts/weak_password/normal.sh",
      },
      {
        "name": "PWN",
        "patch": 450,
        "block": -320,
        "offline": -160,
        "port": 1234,
        "checkpatch": "/root/scripts/linux_pwn/patch.sh",
        "checknormal": "/root/scripts/linux_pwn/normal.sh",
      },
    ],
  },
  {
    "name": "Ubuntu_2",
    "flag": 750,
    "Service": [
      {
        "name": "XSS",
        "patch": 300,
        "block": -250,
        "offline": -125,
        "port": 5555,
        "checkpatch": "/root/scripts/XSS/patch.sh",
        "checknormal": "/root/scripts/XSS/normal.sh",
      },
      # {
      #   "name": "smb",
      #   "patch": 300,
      #   "block": -250,
      #   "offline": -125,
      #   "port": 445,
      #   "checkpatch": "",
      #   "checknormal": "",
      # },
      {
        "name": "SSRF",
        "patch": 300,
        "block": -250,
        "offline": -125,
        "port": 80,
        "checkpatch": "/root/scripts/SSRF/patch.sh",
        "checknormal": "/root/scripts/SSRF/normal.sh",
      },
      {
        "name": "Command_injection",
        "patch": 225,
        "block": -250,
        "offline": -125,
        "port": 81,
        "checkpatch": "/root/scripts/commandinjection/patch.sh",
        "checknormal": "/root/scripts/commandinjection/normal.sh",
      },
    ],
  },

  {
    "name": "Ubuntu_3",
    "flag": 750,
    "Service": [
      {
        "name": "file_upload",
        "patch": 225,
        "block": -250,
        "offline": -125,
        "port": 80,
        "checkpatch": "/root/scripts/file_upload/patch.sh",
        "checknormal": "/root/scripts/file_upload/normal.sh",
      },
      {
        "name": "sql_injection",
        "patch": 300,
        "block": -250,
        "offline": -125,
        "port": 81,
        "checkpatch":  "/root/scripts/sql_injection/patch.sh",
        "checknormal": "/root/scripts/sql_injection/normal.sh",
      },
      {
        "name": "jwt",
        "patch": 400,
        "block": -250,
        "offline": -125,
        "port": 9999,
        "checkpatch": "/root/scripts/JWT/patch.sh",
        "checknormal": "/root/scripts/JWT/normal.sh",
      },
      {
        "name": "dirb",
        "patch": 200,
        "block": -250,
        "offline": -125,
        "port": 82,
        "checkpatch": "/root/scripts/dirb/patch.sh",
        "checknormal": "/root/scripts/dirb/normal.sh",

      },
    ],
  },
]